/*
 * Versão de banco 0.0.1 para contrução da estrutura de dados.
 */
create table tb_lclzo
(
	id_lclzo bigint constraint tb_lclzo_pkey primary key,
	cd_lttde double precision,
	cd_lngte double precision
);
alter table tb_lclzo owner to ifood_marketplace;

create table tb_rstre
(
	id_rstre bigint constraint tb_rstre_pkey primary key,
	nm_rstre varchar(80),
	id_lclzo bigint constraint fk_tb_lclzo references tb_lclzo
);
alter table tb_rstre owner to ifood_marketplace;

create table tb_prato
(
    id_prato bigint constraint tb_prato_pkey primary key,
    ds_prato varchar(500),
    nm_prato varchar(50),
    vl_prato numeric(19,2),
    id_rstre bigint constraint fk_tb_rstre references tb_rstre
);
alter table tb_prato owner to ifood_marketplace;

create table tb_prato_clnte
(
    id_prato_clnte bigint generated by default as identity
        constraint tb_prato_clnte_pkey primary key,
    id_clnte varchar(50),
    id_prato bigint constraint fk_tb_prato references tb_prato
);
alter table tb_prato_clnte owner to ifood_marketplace;

/*
 Carga de informação para facilitar a vida.
 */

INSERT INTO tb_lclzo (id_lclzo, cd_lttde, cd_lngte) VALUES ('1', '15515.5', '-15155.0');
INSERT INTO tb_rstre (ID_RSTRE, NM_RSTRE, ID_LCLZO) VALUES ('1', 'NOME DO RESTAURANTE 1', 1);
INSERT INTO tb_lclzo (id_lclzo, cd_lttde, cd_lngte) VALUES ('2', '15515.6', '-15156.0');
INSERT INTO tb_rstre (ID_RSTRE, NM_RSTRE, ID_LCLZO) VALUES ('2', 'NOME DO RESTAURANTE 2', 2);
INSERT INTO tb_lclzo (id_lclzo, cd_lttde, cd_lngte) VALUES ('3', '15515.3', '-15156.3');
INSERT INTO tb_rstre (ID_RSTRE, NM_RSTRE, ID_LCLZO) VALUES ('3', 'NOME DO RESTAURANTE 3', 3);
INSERT INTO tb_prato (id_prato, ds_prato, nm_prato, vl_prato, id_rstre)
    VALUES ('1', 'Descrição do prato 1', 'prato gostoso 1', '10.99', 1);
INSERT INTO tb_prato (id_prato, ds_prato, nm_prato, vl_prato, id_rstre)
    VALUES ('2', 'Descrição do prato 2', 'prato gostoso 2', '11.98', 1);
INSERT INTO tb_prato (id_prato, ds_prato, nm_prato, vl_prato, id_rstre)
    VALUES ('3', 'Descrição do prato 3', 'prato gostoso 3', '12.97', 1);